### ISSUE TITLE
New working group: wg-actions

### ISSUE THREAD

**Issue by dreamofabear** [ampproject/meta-tsc#11]
I'd like to propose a new working group: `wg-actions`. 

Its responsibility is to oversee development of:
- [`ACTIONS`](https://github.com/ampproject/amphtml/blob/84a002d004fdefa3eae85ef8e8647b9f7abfc472/validator/validator.proto#L447) validator spec
- Related extensions i.e. [`amp-viewer-assistance`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-assistance/amp-viewer-assistance.md) and the upcoming [`amp-viewer-gpay-[inline|button]`](https://github.com/ampproject/wg-ui-and-a11y/issues/9#issuecomment-481374471)

Initial membership:
- @choumx (AMP)
- @jasti (AMP)
- @ianba (AoG)

**Comment by mrjoro** [comment]
@cramforce has the TSC decided the process for approving new WGs? /cc @ampproject/tsc

**Comment by cramforce** [comment]
Can be created if the approvers group agrees.

I'm not so sure this group has enough scope, but happy to be convinced otherwise.

**Comment by dreamofabear** [comment]
@ampproject/wg-approvers Thoughts?

Another option is to fold this under @ampproject/wg-runtime. Fine with either.

**Comment by dreamofabear** [comment]
Going to fold these under @ampproject/wg-runtime until the scope is larger to warrant a split. Thanks for the feedback.
