### ISSUE TITLE
TSC Meeting #9 2019-04-16 AMP Conf Edition

### ISSUE THREAD

**Issue by cramforce** [ampproject/meta-tsc#12]
# Agenda

* Bento AMP deep dive by @dvoytenko 
* @mrjoro & @tobie Could you come in for this to talk governance and AC meeting?
* Discuss foundation

**Comment by tobie** [comment]
Yes. It would be great to get the other @ampproject/ac members present to join too.

**Comment by mrjoro** [comment]
Sounds good!  What time is the meeting at?

**Comment by cramforce** [comment]
Timing is being worked on. Tentative 2:30 pm on Tuesday for 2h

**Comment by sumodas** [comment]
2:30p what time zone, PT?

—
Sumantro Das
E: sumantro.das@gmail.com
P: (845) 558-8313

**Comment by rudygalfi** [comment]
@sumodas This would be Tokyo time because it's being held onsite at AMP Conf.

@cramforce Is there a location?

**Comment by cramforce** [comment]
@ampproject/tsc Proposed time is now 3:30pm. It'll be at the Google office in the same building as the conference venue. We are meeting for the TSC panel tech check at 3pm at the conference venue.
