### ISSUE TITLE
Lack of clarity on how to change a WG facilitator

### ISSUE THREAD

**Issue by nainar** [ampproject/meta-tsc#16]
As a Working Group facilitator stops working in the AMP space, or doesn't want to be facilitator anymore, how do we assign a new Working Group facilitator?

Do we so by consensus of the WG? The initial WG facilitator is picked by the TSC.

cc @mrjoro since I talked to him about it.

**Comment by mrjoro** [comment]
I created a proposed fix (allowing WGs to change Facilitators using the consensus-based approach) in https://github.com/ampproject/meta/pull/39
