### ISSUE TITLE
Request to create OpenJS Foundation onboarding WG

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-tsc#23]
The [onboarding checklist](https://github.com/openjs-foundation/cross-project-council/issues/350) to join the OpenJS Foundation requires a substantial amount of work and coordination between various working groups, the TSC, OpenJS Foundation staff, and Google's OSPO.

Where possible, the plan is to file issues against the various existing working groups or the TSC itself, and track those in an [org-level project board](https://github.com/orgs/ampproject/projects/4).

But that's not possible for all issues, as some pertain to multiple working groups, or to outside organizations or individuals.

From both a project management and a transparency perspective, creating a dedicated working group to host this work feels like the best solution.

We'd be using the WG repo to:
*  communicate the WG's work mode, communication channels, and meeting times,
* file issues which don't have a clearer home in another working group or in the TSC itself.

I'd be happy to facilitate this WG and organize weekly meetings until the mid-December deadline.

Of course, once AMP is fully onboarded, this WG would be sunset.

**Comment by sveronesi** [comment]
I am ok with that.
It'd be great to get regular updates from the WG since the TSC might help and make some decisions.

**Comment by rudygalfi** [comment]
I'm supportive of this plan.

**Comment by paularmstrong** [comment]
👍 sounds great

**Comment by cpapazian** [comment]
👍

**Comment by cramforce** [comment]
👍

**Comment by davidstrauss** [comment]
+1 :-)

**Comment by dvoytenko** [comment]
👍

**Comment by rudygalfi** [comment]
It appears that the consensus of the TSC is to move forward with the plan described.

**Comment by mrjoro** [comment]
Great!

I've created the [wg-foundation-onboarding repo](https://github.com/ampproject/wg-foundation-onboarding), [team](https://github.com/orgs/ampproject/teams/wg-foundation-onboarding) and [Slack channel](https://app.slack.com/client/T0ADHJGD6/CPQL19SCV).

**Comment by tobie** [comment]
Thanks all, folks!

Also great to see that this is such a lightweight process. Congrats!!
