### ISSUE TITLE
Create a working group for Bento

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/meta-tsc#24]
Likely a temporary working group until it's ready to be merged into an existing working group. But, anticipating aa wide-ranging set of design documents and issues this will benefit from a working group at this time.

Facilitator: @dvoytenko

**Comment by rudygalfi** [comment]
This was approved in the 2019-11-06 TSC meeting

**Comment by mrjoro** [comment]
I'll create the repo and team & update docs.

**Comment by mrjoro** [comment]
I have created the wg-bento [repo](https://github.com/ampproject/wg-bento), [team](https://github.com/orgs/ampproject/teams/wg-bento/members) and [Slack channel](https://app.slack.com/client/T0ADHJGD6/CQ23HCDQR).

I also have a [PR to add wg-bento to the working-groups README](https://github.com/ampproject/meta/pull/47).

**Comment by dvoytenko** [comment]
Thanks so much, @mrjoro!
