### ISSUE TITLE
Create a Security and Privacy Working Group

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#26]
I propose creating a Security and Privacy Working Group (wg-security-privacy).  This working group's charter would be:

_Responsible for ensuring AMP maintains high standards with respect to security and privacy, including documenting security/privacy best practices and facilitating security/privacy reviews for AMP code and features._

The initial members of this group would be:
- @honeybadgerdontcare (David Sedano, facilitator)
- @molnarg (Gábor Molnár)

This working group would be responsible for supporting the security/privacy parts of the [proposed launch process](https://docs.google.com/document/d/1bF5tHbm-ObyjKLfoiIEAI5V-YvMsA3Bchsux5u4cKZM/edit).

/cc @ampproject/tsc @nainar

**Comment by sveronesi** [comment]
For some reason, I thought we already had this WG. 
We currently don't have anyone looking at this? How does security reviews work?

**Comment by mrjoro** [comment]
In the past we've primarily had security and privacy teams at Google that review issues that may be of concern.

Part of the reason for this WG is to make this more transparent.  Another goal would be to include security/privacy experts outside Google in the WG as well.

**Comment by mrjoro** [comment]
I'm hoping the TSC can approve this WG offline so we can move forward with creating it and I don't _think_ it's controversial, but let me know if there are any concerns.

**Comment by rudygalfi** [comment]
LGTM

**Comment by dvoytenko** [comment]
LGTM

**Comment by sveronesi** [comment]
LGTM

**Comment by mrjoro** [comment]
I see LGTMs/thumbs up from 4 members of the TSC.  @cramforce @davidstrauss @paularmstrong are y'all okay with creating the security & privacy WG, or should it be discussed at the next TSC meeting?

**Comment by cramforce** [comment]
LGTM

**Comment by ssantosms** [comment]
LGTM

**Comment by rudygalfi** [comment]
Approved by the TSC

**Comment by mrjoro** [comment]
I've create the slack channel, team and repo:

https://github.com/ampproject/wg-security-privacy
