### ISSUE TITLE
Decide whether & when to invite people to the ampproject org automatically

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#28]
https://github.com/ampproject/meta/issues/20 proposes inviting people automatically to the ampproject org.

We'd like the TSC to give guidance on:
A) Should we invite people automatically to the ampproject org.
B) If yes to A, what should trigger the automatic invitation (e.g. any comment, and issue filed, any PR filed?).

The advantage of membership in the ampproject org is that members of the org can be assigned issues and more easily be @ mentioned on issues, plus intangibles like being part of the community.

Today we grant membership to everyone who fills out a [form](https://docs.google.com/forms/d/e/1FAIpQLSeF1PN4Ee7Ke5Hvn4uN_oznV3isr-tfFg7cFRLX2F2OJGhXpw/viewform?c=0&w=1) requesting membership.

Inviting people automatically may be considered spammy by some.

Note that GitHub now charges per org member for their normal plan, but not for the GitHub Teams for Open Source plan (which we'll be on once I work through some issues with GitHub support).

**Comment by rudygalfi** [comment]
Approved by TSC, provided we clarify that our process entails automatic approval to be part of the Github org without a manual review.

**Comment by mrjoro** [comment]
Which option was approved? :)

**Comment by davidstrauss** [comment]
> Which option was approved? :)

We agreed to "yes" on item A, but I'm not sure we established any criteria for B. I could be wrong, but I'm not sure that the TSC wants to explicitly decide item B. The feeling from the meeting seemed to be that adding people to the project should be done permissively and with minimal bureaucracy. (Correspondingly, no one should interpret membership in the GitHub project as much more than inclusion in the list of allowed bug assignees, and we should make that clear.)

Since I'm not sure that answers your question or reflects TSC consensus, I'll reopen this one.

**Comment by davidstrauss** [comment]
The TSC discussed how to balance efficiency for assignments against not being spammy. It seems to come down to not wanting to be blocked by lack of org membership when wanting to perform the assignment. So, can we directly confront this issue?

What we'd like to consider is a bot that detects a comment like "/tryassign @EXAMPLE". If @EXAMPLE is not yet in the AMP org, they get an invite. If they accept the invitation, the bot can assign the issue/PR to them. This could occur on a later pass through issues, on the event of the acceptance, or through any other method.

**Comment by amanintech** [comment]
Is this already Implemented ?

**Comment by mrjoro** [comment]
We haven't yet implemented this.

I wonder how hard it would be to modify one of the bots @ampproject/wg-infra has created to do this.  /cc @rcebulko

**Comment by rcebulko** [comment]
We probably wouldn't want to just tack this onto an existing bot, but from a technical point of view this wouldn't be too difficult

**Comment by rsimha** [comment]
> We probably wouldn't want to just tack this onto an existing bot, but from a technical point of view this wouldn't be very difficult

We maintain a handful of bots that perform various automated tasks using the `ampprojectbot` GH account. It's definitely feasible to implement a workflow that invites contributors to `ampproject`. We can use the guidelines in https://github.com/ampproject/meta-tsc/issues/28#issuecomment-567227934 and track this via a feature request I just filed: https://github.com/ampproject/amp-github-apps/issues/687

**Comment by rcebulko** [comment]
In the I2I thread, one question that came up is, who should be able to trigger this /invite macro? Presumably we don't wont anyone to be able to just /invite themselves.

It would seem sensible that either a) anyone in `ampproject/reviewers-amphtml` be able to or b) anyone already a member of `ampproject`

**Comment by mrjoro** [comment]
I'm in favor of making it anyone in ampproject/reviewers-amphtml for now; we can expand later if needed.

**Comment by rcebulko** [comment]
@mrjoro May I suggest creating something along the lines of `ampproject/meta-inviters` and for now adding `ampproject/reviewers-amphtml` to that Team? Then, if you want to expand the allowed list, you could just add ex. `ampproject/meta-tsc` to `ampproject/meta-inviters` and you wouldn't even need me to change any configurations!

**Comment by rcebulko** [comment]
The bot has been written and is fully operational, currently running on a test organization I created. It can be installed on `ampproject` whenever y'all are ready.

Any time a comment, PR description, review, or issue description contain `/invite @user` it will send out an invite (and comment that it has), and will update the thread when the invite is accepted. `/tryassign @user` will do the same, but will also assign the issue once the invite is accepted. If the user is already a member, `/invite` will result in a comment indicating as much, while `/tryassign` will immediately assign the user to the issue.

![image](https://user-images.githubusercontent.com/6694512/74574751-aa390e80-4f52-11ea-942a-fc7b269be095.png)

**Comment by rcebulko** [comment]
Evidence would suggest the bot is installed and running on all repositories in `ampproject`!

/tryassign @rcebulko

**Comment by rcebulko** [comment]
Can we close this?

**Comment by mrjoro** [comment]
Yes!  Thanks @rcebulko!

**Comment by rcebulko** [comment]
Shoutout to @danielrozenberg for reviewing the bulk of this PR deluge! :clap: :clap: :clap:

**Comment by davidstrauss** [comment]
Great work. I love seeing this come to fruition. :-)
