### ISSUE TITLE
Do we need a deadline for design review topic submissions?

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/meta-tsc#29]
Sometime design review topic submissions come in with relatively little time before design review occurs, arguably beyond the time that's reasonable for adequate notice to the community. Should we enforce a notice deadline?

A couple thoughts on this:
- Not enforcing a specific deadline but instead prioritizing earlier topic proposals would generally have the effect of encouraging earlier submissions. It would have a failure mode of enabling topics with "insufficient" notice to still proceed if there is a small number of design review topics in a given week.
- What is considered notice? Is it posting to the design review issue? To the I2I issue? Both?

**Comment by dvoytenko** [comment]
Not sure as a policy, but I wish that the topics were submitted with underlying documents 24hr prior.

**Comment by mrjoro** [comment]
We currently state that topics should be added to the design review issue by the Monday before the Wednesday design review (with no specific time mentioned), but we don't enforce this.

We could change this to 24 hours (which would be more global friendly), and post a comment at 24 hours saying "topics are closed for this week."

**Comment by rudygalfi** [comment]
Policy is stated in https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review

**Comment by davidstrauss** [comment]
Consensus from the TSC is that we will keep the current Monday deadline as the official process and clarify good justifications for bending the process as part of an upcoming "Guidelines for Design Review Meetings" (title is possibly paraphrased).
