### ISSUE TITLE
Collaborator / OWNER status requirements

### ISSUE THREAD

**Issue by cramforce** [ampproject/meta-tsc#3]
A proposal for rules surrounding getting Collaborator and/or OWNER status in AMP.

These rules apply for the main AMP JS repository https://github.com/ampproject/amphtml. Other repos may pick a different process.

## Basics

- See our [glossary](https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#glossary) for definitions of terms.
- These rules are pending the launch and successful security review of https://github.com/google/github-owners-bot for a repository. This project while reusable is being developed specifically for AMP.
- TODO: Add link to comprehensive docs of OWNERS system.

## Ground rules

- All pull requests require code review and approval from a collaborator who is not the author.
- All pull requests require code review and approval from a reviewer.
- All pull requests require code review and approval from an OWNER of the effected files (may be the same person as the general reviewer, not required if the author is an OWNER of the respective files themselves).

## Collaborator status

- Collaborator status is granted to folks who have proven basic familiarity with the respective repository.
- This is granted after 2 merged PRs.
- Qualifying PRs must be non-trivial (not only fixing typos, not only config changes).

## Reviewer status

- Reviewer status is granted to folks who have demonstrated deep familiarity with the code-style and conventions of the respective repository.
- This is granted after 10 merged PRs and a +1 from 1 reviewer.
- Alternatively it may also be granted after 10 high quality reviews of complex PRs and a +1 from 1 reviewer.
- Qualifying PRs must be non-trivial (not only fixing typos, not only config changes) and should have implemented or documented at least 2 new features.

## Owner status

- Owner status is granted by higher-level owners (in the directory hierarchy) at their discretion.
- When creating a new directory (such as when creating a new AMP extension) the author of the pull request should designate themselves as OWNER.
- All GitHub users including those who are not collaborators can be owners.

**Comment by cramforce** [comment]
From @davidstrauss: Provide alternative path to become a reviewer, where the quality of the review counts as opposed produced code.

**Comment by cramforce** [comment]
CC @erwinmombay

**Comment by cramforce** [comment]
CC @mrjoro

**Comment by cramforce** [comment]
Brought this in line with discussion from last @ampproject/tsc meeting. @mrjoro Do we have a link yet for that TODO regarding description of OWNERS system?

**Comment by mrjoro** [comment]
Not yet.  Are you looking for a description of the OWNERS.yaml files and who should go in there, i.e. an updated version of the [owners-and-committers](https://github.com/ampproject/amphtml/blob/master/contributing/owners-and-committers.md#owners)?

**Comment by cramforce** [comment]
Add process for applying for a role: File a GitHub issue with a particular template. To be refined.

**Comment by cramforce** [comment]
Process is approved by the TSC.

**Comment by mrjoro** [comment]
Fixed by #21280.
