### ISSUE TITLE
Create/document a process for deciding which projects to contribute to through the Open Collective

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#30]
AMP currently [contributes to many projects](https://opencollective.com/amp#section-contributions) through Open Collective.

The process for deciding which projects to contribute to is not currently documented.  I propose that the TSC be responsible for this.

The process should indicate:
- Who can propose a project to fund
- Whether proposals and the resulting discussions should be public
- How the TSC decides which projects to fund

Note that currently the AMP's Open Collective contributions are funded by Google.  The mechanism by which this funding will happen assuming AMP successfully completes the OpenJS Foundation onboarding is under discussion.

/cc @ampproject/tsc @tobie @pbakaus

**Comment by mrjoro** [comment]
From the TSC meeting, the process will be:

- collect proposals for Open Collective funding via a public GitHub issue, making sure to let the AC know about this
- the TSC will discuss the proposals at a meeting in January 2021 and make decisions on how to allocate funding

I will file an issue with the following text to collect proposals.  **Members of the @ampproject/tsc** please let me know if there are any changes you'd make, especially if there is more/different information you'd like to see in the proposals.

-----

The AMP Project [provides financial support](https://opencollective.com/amp) to other open source projects that make AMP possible or that otherwise align with [AMP's vision](https://amp.dev/about/mission-and-vision/) of a strong, user-first open web forever.

We provide this funding via [Open Collective](https://opencollective.com/).  You can see the projects AMP has funded in the past on [AMP's Open Collective page](https://opencollective.com/amp).

Members of the AMP community are invited to propose which projects AMP Project will provide Open Collective funding to in 2021.  AMP's Technical Steering Committee will use these proposals as input when determining how to allocate AMP's 2021 Open Collective funds in January 2021.

To make a proposal, respond to this GitHub issue with a comment including:
- the name of the project and a link to their Open Collective page
- a brief description of the project
- a brief description of how AMP is positively impacted by the project and/or how the project aligns with [AMP's vision](https://amp.dev/about/mission-and-vision/) of a strong, user-first open web forever.

Proposals are due January 8, 2021.

**Comment by rudygalfi** [comment]
LGTM

**Comment by mrjoro** [comment]
friendly ping to the TSC members on the wording of the call for proposals, especially whether the requested info will be enough to help make a decision on which projects to fund

**Comment by mrjoro** [comment]
I'll assume there are no contrary opinions, and with Rudy's LGTM I'll go ahead and post the issue.  :)

**Comment by dvoytenko** [comment]
LGTM

**Comment by mrjoro** [comment]
Filed https://github.com/ampproject/meta-tsc/issues/56
