### ISSUE TITLE
Provide guidelines for proposing design review topics

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#31]
The current [guidelines for design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review) provides two ways for sharing topics for discussion in a design review:

- a public design doc (shared as a public Google Document)
- an I2I

In practice we have also allowed a wide variety of other mechanism, including:

- a non-public design doc (generally a Google-internal doc, usually with no Google-internal information)
- a non-I2I GitHub issue
- a simple comment in the design review issue ("I want to discuss X")

We should provide more clear guidelines on how people can and should bring topics to a design review so that the guidelines match our actual practices.

My proposal is to:
- Encourage
  - explainers (e.g. https://github.com/ampproject/wg-bento/pull/1) for major topics
  - non-I2I GItHub issues for smaller topics that don't warrant a full explainer, design doc or I2I, where the issue has enough context for anyone in the community to participate in the discussion
- Allow
  - public design docs
  - I2Is
- Disallow
  - comments in the design review issue not described by a separate GitHub issue
  - non-public docs

Topics not proposed using one of the Encouraged or Allowed formats would not be discussed at the design review.

/cc @ampproject/tsc @ampproject/reviewers-amphtml @ampproject/collaborators-amphtml

**Comment by davidstrauss** [comment]
+1 on this proposal. I also support @dvoytenko's work to make the process transparent/public by the nature of the process (avoiding inadvertent under-sharing).

**Comment by sveronesi** [comment]
+1. Supportive of this.

**Comment by mrjoro** [comment]
OK; if there are no objections I'll go ahead and update the docs to reflect this proposal.
