### ISSUE TITLE
Publish quarterly roadmap of WGs at draft stage for feedback

### ISSUE THREAD

**Issue by aghassemi** [ampproject/meta-tsc#33]
One of the items discussed in the last AC meetings was the need for AC to have better visibility into high-level upcoming work in WGs early so that AC can provide feedback before commitment is made on those items.

I like to explore possibility of WGs publishing their quarterly planning docs when at draft stage with AC. A variation of this could be TSC publishing the consolidated planning doc that rolls up WGs plans.

/cc @ampproject/tsc @tobie

**Comment by cramforce** [comment]
The TSC discussed this issue and we're wondering: 

Would it make sense to add a forward-looking component to the current backward-looking working group reports? https://github.com/ampproject/meta/wiki/Working-Group-Updates
Basically each working group would include a roadmap part in this roughly quarterly report.

**Comment by aghassemi** [comment]
I believe that's a good place. Some WGs have provided high-level "what's next" in their reports in the past. Formalizing this and ensuring there is enough details on the roadmap items ( e.g. links to ITI if there is one ) would be great.

/cc @ampproject/ac

**Comment by cramforce** [comment]
@mrjoro Could we update the guidelines for the working group updates to contain a forward looking section?

**Comment by rudygalfi** [comment]
cc @sebastianbenz and @nainar who may also have updates.

**Comment by mrjoro** [comment]
The instructions for the [quarterly WG updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) did mention including plans for the upcoming quarter as well as backward-looking updates, and looking through the last few updates it looks like most WGs are including these.  Not all have, so I've updated the top of the updates page to make this more clear and we'll remind WGs of this in the future.

**Comment by nainar** [comment]
I think the next step is what Joey said - to make sure all WGs have a What's Next section. We should as a community make sure to call out any update that doesn't have this section. 

WIP: We will also be updating the Roadmap at https://amp.dev/community/roadmap/ to have WG updates instead of it's current format. 

That way visitors can understand what each WG has achieved/intends to achieve on a rolling basis.

**Comment by rudygalfi** [comment]
@nainar Is there another update you can provide here about the WIP item?

**Comment by nainar** [comment]
@sbenz to confirm...

The @ampproject/wg-outreach has mocks ready of what the new Roadmap page would look like. 
I don't know what the status/timeline on execution is.

**Comment by sebastianbenz** [comment]
The new page is currently being worked on. The import functionality is done
and we're currently working on the UI. Should be live in the next two weeks.

>

**Comment by rudygalfi** [comment]
The new page is live at: https://amp.dev/community/roadmap/

**Comment by rudygalfi** [comment]
Does the revision to the [roadmap page](https://amp.dev/community/roadmap/) on amp.dev meet the needs expressed here? I will close this out for now, but please re-open with any further suggestions.
