### ISSUE TITLE
TSC Meeting #24 2020-05-06 20:00 UTC

### ISSUE THREAD

**Issue by cramforce** [ampproject/meta-tsc#39]
## Agenda

* Could the TSC get an update the OpenJS Foundation process? @tobie @mrjoro 
* CLA process within foundation
* Review [TSC issue backlog](https://github.com/ampproject/meta-tsc/issues?q=-label%3A%22TSC+Resolved%22+is%3Aopen)
* Review [TSC-tagged issues](https://github.com/issues?q=team%3Aampproject%2Ftsc+sort%3Aupdated-desc+-label%3A%22TSC+Resolved%22) (toggle to "open" after checking for recently "closed" items)

**Comment by cramforce** [comment]
Everybody loves the CLA tool that @tobie presented! #25

**Comment by rudygalfi** [comment]
- Could the TSC get an update the OpenJS Foundation process? @tobie @mrjoro
   - Shared board being used to track tasks. Most are done. 5 in progress, 1 to do.
   - Plan to announce onboarding at OpenJS World / AMP Contributor summit June 23-24
- CLA process within foundation
   - TSC tested this out and seems good to go
- Review TSC issue backlog
   - From Rudy: Roadmap is coming along
- Review TSC-tagged issues (toggle to "open" after checking for recently "closed" items)
   - Nothing new
