### ISSUE TITLE
I2I: Pixi - AMP page experience guide

### ISSUE THREAD

**Issue by nainar** [ampproject/meta-tsc#50]
## Introduction
The AMP page experience guide aka Pixi is a tool that shows AMP developers how their AMP pages are performing against the Google Search page experience ranking signal, and provides actionable feedback on how they can improve. To do the analysis we use publicly available APIs such as PageSpeed Insights, Safe Browsing, and Mobile-friendliness Test.

[Design Doc](https://docs.google.com/document/d/18dqzgCPiagpZQ_1bOf8Eg9nJvJ5WPrfhL3x84xyIXJo/edit#)
[Reference image](https://cdn.zeplin.io/5d124579276e2a7085d277cf/screens/984E6CB6-2450-4733-8213-726F7DB8AD6E.png)
**[WIP Staging experience](https://amp-dev-staging.appspot.com/page-experience/)** <- Please try! Leave feedback by filing a GitHub issue on [amp.dev GH repo](https://github.com/ampproject/amp.dev)

## Motivation
- Provide AMP specific actionable feedback to developers to help them perform better on the signals that make up page experience. E.g. use the AMP optimizer, ensure that a component is set up correctly. 
- Put AMP in a state where we guarantee that in cases that an AMP page doesn't meet page experience signals we are able to either provide actionable feedback or are able to provide support to help address that issue so that the AMP page falls into a situation where the AMP page does do well on page experience. 

## Launch plan
- AMP Fest will be the first moment we publicly release Pixi to the public. 
- We will accompany the release of Pixi with the following blog posts:
  - Introducing Pixi
  - How Pixi was made - talking about how it uses <amp-script>
  - New AMP Optimizer launches - e.g hero image preloading and module/no module support

**Comment by nainar** [comment]
@ampproject/tsc to review

**Comment by davidstrauss** [comment]
@nainar This is really neat work! I'm excited to see how this shapes up. I raised some topics at today's TSC meeting around better explaining/quantifying AMP benefits to CWV, and a couple people mentioned your work on Pixi.

**Comment by sveronesi** [comment]
This is great. Nice job

**Comment by rudygalfi** [comment]
@nainar Can this be closed out?

**Comment by nainar** [comment]
Marking as Launched and closing
