### ISSUE TITLE
Freeze releases for US elections, October 26 - November 8, 2020

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#51]
I'm filing this issue to get TSC approval per the [release-freeze guidelines](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#release-freezes).

In past years, we have traditionally frozen the release of AMP around US elections given the stability requested by news publishers for this major news event.

We now have the [Long Term Stable (LTS) release](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#long-term-stable-lts) available for sites that desire additional stability, and I would recommend publishers use this in the future.  

Publishers may not have adopted LTS yet given this is the first year it is available, so I recommend we continue with the US election release freeze this year, but that we publicize that in future years publishers who require extra stability around certain events should use LTS.

to @ampproject/tsc for approval
/cc @ampproject/wg-infra @ampproject/wg-access-subscriptions @rsimha @jpettitt @nainar

**Comment by rsimha** [comment]
Bumping this issue to check if we have TSC approval for this.

**Comment by dvoytenko** [comment]
+1

**Comment by rudygalfi** [comment]
I approve of this.

I also want to reflect that @davidstrauss appears to have given a thumbs up on the original issue post.

**Comment by nainar** [comment]
Confirming that this request is for a one week release freeze?

**Comment by mrjoro** [comment]
I've been assuming we'll freeze the release the week before and the week of the election:
- The week before would be for the lead up to the election and the election itself (on Tuesday, November 3)
- the week of the election because it's uncertain how long it will be before the results of the election are fully known

**Comment by sveronesi** [comment]
I approve this as well. It's critical AMP documents to be in a stable condition in that timeframe.

**Comment by paularmstrong** [comment]
+1 approval, including clarification of week leading up to and of election
@mrjoro Could you amend this as start and end date for clarity?

**Comment by rudygalfi** [comment]
This is TSC approved per our Oct 7 meeting. We provided further guidance about ensuring the LTS release schedule is covered in this proposal and that LTS is also stable.

**Comment by mrjoro** [comment]
@rsimha can we ensure that a new LTS does not get pushed during this freeze as well?

**Comment by rsimha** [comment]
> @rsimha can we ensure that a new LTS does not get pushed during this freeze as well?

I can confirm that our internal release automation system now has a blocking check that will prevent Stable channel and LTS channel promotions during the freeze period.

**Comment by mrjoro** [comment]
Great!

Is there anything else needed before we can close this issue?

**Comment by rudygalfi** [comment]
The TSC has been assessing the need to extend this freeze, but the TSC consensus is to **not** extend the freeze.
