### ISSUE TITLE
Proposals for AMP Project Open Collective funding (due Jan 8, 2021)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta-tsc#56]
The AMP Project [provides financial support](https://opencollective.com/amp) to other open source projects that make AMP possible or that otherwise align with [AMP's vision](https://amp.dev/about/mission-and-vision/) of a strong, user-first open web forever.

We provide this funding via [Open Collective](https://opencollective.com/).  You can see the projects AMP has funded in the past on [AMP's Open Collective page](https://opencollective.com/amp).

Members of the AMP community are invited to propose which projects AMP Project will provide Open Collective funding to in 2021.  AMP's Technical Steering Committee will use these proposals as input when determining how to allocate AMP's 2021 Open Collective funds in January 2021.

**To make a proposal, respond to this GitHub issue with a comment including:**
- the name of the project and a link to their Open Collective page
- a brief description of the project
- a brief description of how AMP is positively impacted by the project and/or how the project aligns with [AMP's vision](https://amp.dev/about/mission-and-vision/) of a strong, user-first open web forever.

Proposals are due January 8, 2021.

**Comment by alanorozco** [comment]
### [Storybook](https://opencollective.com/storybook)

> Storybook is an open source tool for developing UI components in isolation for React, Vue, Angular, and more. It makes building stunning UIs organized and efficient.

AMP is planning to release all examples (ampproject/amphtml#30954, classic AMP, and Bento) in an interactive UI to configure and test component themselves. This helps both the project's development flow and that of other projects that use AMP components. We'll also be using Storybook samples as an input for automated testing.

**Comment by alanorozco** [comment]
### [Prettier](https://opencollective.com/prettier)

> An opinionated code formatter

Prettier hasn't only helped us have a nicer, more straightforward development experience, but has become critical in maintaining consistency in code output automatically generated by several of our tools.

**Comment by jridgewell** [comment]
### [Babel](https://opencollective.com/babel)

> Babel is the community maintained compiler for evolving the future of JavaScript

Babel improves the entire web ecosystem by allowing developers to use the newest JavaScript features _before_ they're added to browsers. I personally consider it to be the most important JS OS project, and its impact on the the web is massive. AMP uses its `preset-env` transformer suite to power our ESM modules, and we implement dozens of custom transformers to ease development.

**Comment by jridgewell** [comment]
### [Preact](https://opencollective.com/preact)

> 3kb alternative to React with the same ES6 API.

Preact is a considerably lighter alternative to React, and the entire Bento project is built on top of it. Preact will soon become a core piece of runtime code powering websites.

**Comment by jridgewell** [comment]
### [ESLint](https://opencollective.com/eslint)

> The pluggable linting utility for JavaScript and JSX

Linters are how we ensure our codebase is consistent between developers and free of bad JS practices. We have a few dozen lint rules running, and have another dozen custom rules we've written ourselves.

**Comment by tobie** [comment]
### [Contributor Covenant](https://opencollective.com/contributor-covenant)

> The world's first and most popular code of conduct, with over 40,000 adoptions.

The Contributor Covenant is the code of conduct used by the OpenJS Foundation and therefore by AMP. It helps keep the AMP community and the broader OpenJSF community safe, inclusive, and welcoming.

Despite its industry-wide impact, the Contributor Covenant, like other non-code contributions to open source, is only rarely recognized as an important part of open source infrastructure. Doing so is important.

**Comment by mrjoro** [comment]
This is a great collection of projects!

Members of the @ampproject/tsc , how do you want to approach making a decision on which projects to fund and the level of funding for each?  I see that for the Feb 10 meeting there's an item on the agenda that'll take the bulk of the time, so should we bring this for discussion on the Feb 24 meeting?

**Comment by tobie** [comment]
As discussed in the last TSC meeting, I have reached to all six projects to ask if they had specific initiatives they were looking to fund on top of getting help with day-to-day maintenance. I'll sync with @mrjoro and we'll report back to the TSC once I've heard back from all projects.

**Comment by mrjoro** [comment]
@tobie do we have a sheet/doc with the finalized sponsorships?  I can initiate the process of distributing the money.

**Comment by tobie** [comment]
@mrjoro absolutely, see: https://docs.google.com/spreadsheets/d/1TTcZwGl7ZptKLmr1o3vuSySonyJsj7l_YGwXupV5tTQ/edit

**Comment by mrjoro** [comment]
We have now made the sponsorships approved by the TSC.  These are visible on the [AMP Open Collective Budget page](https://opencollective.com/amp/transactions).
![Screen Shot 2021-06-21 at 9 49 31 AM](https://user-images.githubusercontent.com/24625776/122799120-35789180-d276-11eb-9cda-632ae4af383d.png)
