### ISSUE TITLE
TSC Meeting #4 2019-02-13

### ISSUE THREAD

**Issue by davidstrauss** [ampproject/meta-tsc#6]
# Agenda
* Discuss [AC <-> TSC communication](https://github.com/ampproject/meta-ac/issues/7)

@ampproject/tsc

We're a week out from this meeting, so I figured I'd create an issue for any agenda items. I think we should consider rescheduling, though, as this conflicts with a design review (Americas region).

# Notes:

- Overall a short meeting
- Switch to mode where we only meet 2x out of 6 weeks and make the 3 meeting coincide with the design review.

## Discuss AC <-> TSC communication

Have Tobie come to the next TSC meeting to let us know how it went and any questions that came up. Rudy to do this.

**Comment by rudygalfi** [comment]
I'd like to discuss [AC <-> TSC communication](https://github.com/ampproject/meta-ac/issues/7)

**Comment by jeffjose** [comment]
One from my side - 

### Contributing amp-google-pay to ampproject repo
amp-google-pay is a component built by [Actions on Google](https://developers.google.com/actions/) to enable payments on their product. It is currently Google internal-only and the team wishes to contribute the code to public repo. I'd like to discuss ownership plan and how it fits into AMP's Payment strategy.

**Comment by davidstrauss** [comment]
@jeffjose Hi Jeff. Have you brought the component to a [design review](https://github.com/ampproject/amphtml/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Design+Review%22)? I'm a little new here still, but that's where I've been seeing most component proposals raised.

**Comment by jeffjose** [comment]
@davidstrauss It might be a little late for design review at this point :) The component was built last year with the help of AMP engineers but the code is owned by the non-AMP team. They wish to upstream the changes, which now puts the responsibility on AMP team. I'm looking to get guidance on what team should own this (if at all) and how this plays into (the future) AMP Payment strategy.

**Comment by rudygalfi** [comment]
@davidstrauss I know a component of this discussion is to come up with an appropriate multi-vendor strategy. @jeffjose Is there a way to define the problem statement in terms of something that would make sense for the TSC to weigh in on first as opposed to design review?

**Comment by jeffjose** [comment]
Thanks for the clarification, @rudygalfi.

@davidstrauss One part of the guidance I want is whether we can accept the code from the Actions on Google team behind an origin trial (ie: allow the code to be used from a preapproved set of domains) since it is a requirement from their end. Do we want to set a precedence like that in the repo?

**Comment by cramforce** [comment]
Design review hangout going on now https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev

**Comment by dreamofabear** [comment]
What was the outcome of this meeting?

@jeffjose @davidstrauss The component did go through design review last year FYI.

I2I: https://github.com/ampproject/amphtml/issues/15201
Design review meeting notes: https://github.com/ampproject/amphtml/issues/18658#issuecomment-434853388

**Comment by jeffjose** [comment]
We didnt put this on the agenda for TSC since we dont yet have a plan for payments in AMP.

**Comment by yazdotdev** [comment]
@jeffjose Why do you not have a plan for payments in AMP?  There is a products page [example](https://ampbyexample.com/samples_templates/product_page/).  But if there is no accompanying amp payments component, it is not particularly useful.

**Comment by jeffjose** [comment]
@yazdotdev - I think we're aligned on the thinking here. 'amp-google-pay' from the previous comment makes few assumptions on the environment it is run on, in particular, that pay.js is available, which would render it useless for AMP pages on the open-web.

The payment plan that I've been spearheading is thinking about how we can bring a generalized solution for payment on AMP pages, that supports all payment providers, including Google Pay.
