### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/meta-tsc#61]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by mrjoro** [comment]
I've made this change. AFAICT there were no links to the old master branch that needed updating, though the GitHub change would cause these links to [properly redirect automatically](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/) anyway.
