### ISSUE TITLE
TSC Meeting 2021-12-15

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/meta-tsc#75]
Please add topics for the agenda as comments on this issue.

The standing agenda items are:

* Review [TSC issue backlog](https://github.com/ampproject/meta-tsc/issues?q=-label%3A%22TSC+Resolved%22+is%3Aopen)
* Review [TSC-tagged issues](https://github.com/issues?q=team%3Aampproject%2Ftsc+sort%3Aupdated-desc+-label%3A%22TSC+Resolved%22) (toggle to "open" after checking for recently "closed" items)

@ampproject/tsc

**Comment by warrenders** [comment]
Additional agenda item:  Review Web Stories updates and year in review.

**Comment by mrjoro** [comment]
@warrenders has indicated it would be preferable to move the Web Stories update to next year.

Are there any other items on the agenda?  If not, we will cancel today's meeting.

**Comment by mrjoro** [comment]
Since there are no items on the agenda, we'll go ahead and cancel this meeting.
